### ISSUE TITLE
Extra labels on issues

### ISSUE THREAD

**Issue by memborsky** [rtyler/Hubboard#16]
Include an additional line for extra labels on issues so you can see what the issues are filed under (Outside of open, in-progress, closed/resolved).

Example -
# [Issue #] - user / repository: [Issue Title]

Labels: [Issue Labels]
[Issue Text]

**Comment by rtyler** [comment]
Starting work on this now.

(_This message brought to you by [Hub board](http://hubboard.herokuapp.com/about)_)
