### ISSUE TITLE
Comment "double click" issue

### ISSUE THREAD

**Issue by memborsky** [rtyler/Hubboard#47]
When double clicking to bring up the pop up box for comments off of an issue the "View on GitHub" has enter focus. I feel this is going to force a lot of miss clicking and should be found to be prevented from happening for the sake of keyboard navigators.

**Comment by rtyler** [comment]
Any thoughts on what should have focus in the dialog?

I'm thinking there should be a comment box that should probably have focus.

**Comment by memborsky** [comment]
The title of the pop up box should probably have it.

**Comment by rtyler** [comment]
Starting work on this now.

(_This message brought to you by [Hub board](http://hubboard.herokuapp.com/about)_)
